-- ============================================================
-- AquaFlow Tracker — Supabase Database Table Schema
-- Run this in your Supabase SQL Editor (https://supabase.com)
-- Safe to re-run: uses IF NOT EXISTS / DROP ... IF EXISTS.
-- ============================================================

-- 1. Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    contact_number TEXT,
    address TEXT,
    container_owned INT DEFAULT 0 CHECK (container_owned >= 0),
    registration_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT UNIQUE NOT NULL,
    product_name TEXT NOT NULL,
    price_per_unit NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (price_per_unit >= 0),
    description TEXT,
    stock_available INT DEFAULT 0 CHECK (stock_available >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    customer_id TEXT NOT NULL REFERENCES public.customers(customer_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity >= 1),
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (total_amount >= 0),
    order_date DATE DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Order status must match the app's allowed values (Pending / Delivered)
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE public.orders
    ADD CONSTRAINT orders_status_check CHECK (status IN ('Pending', 'Delivered'));

-- 4. Collections Table
CREATE TABLE IF NOT EXISTS public.collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id TEXT UNIQUE NOT NULL,
    customer_id TEXT NOT NULL REFERENCES public.customers(customer_id) ON DELETE CASCADE,
    order_id TEXT REFERENCES public.orders(order_id) ON DELETE SET NULL,
    empty_jugs_returned INT DEFAULT 0 CHECK (empty_jugs_returned >= 0),
    filled_jugs_released INT DEFAULT 0 CHECK (filled_jugs_released >= 0),
    container_balance INT DEFAULT 0 CHECK (container_balance >= 0),
    collection_date DATE DEFAULT CURRENT_DATE,
    collected_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Users Table (login accounts — passwords are stored as hashes, never plain text)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('admin', 'delivery', 'customer')),
    customer_id TEXT REFERENCES public.customers(customer_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- RLS is ON for every table with NO public policies.
-- => The public/anon key cannot read or write anything.
-- => The Flask backend uses SUPABASE_SECRET_KEY, which bypasses RLS,
--    and enforces login + role checks itself.
-- ============================================================
ALTER TABLE public.customers   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users       ENABLE ROW LEVEL SECURITY;

-- Remove the old "anyone can do anything" policies if they were created before
DROP POLICY IF EXISTS "Allow public all on customers"   ON public.customers;
DROP POLICY IF EXISTS "Allow public all on products"    ON public.products;
DROP POLICY IF EXISTS "Allow public all on orders"      ON public.orders;
DROP POLICY IF EXISTS "Allow public all on collections" ON public.collections;
